// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjGXEk49YfYNtqSveFfdBmCgaYJwtolmE',
    appId: '1:459352817410:web:41c725142756e5419ecc1b',
    messagingSenderId: '459352817410',
    projectId: 'card-flex',
    authDomain: 'card-flex.firebaseapp.com',
    storageBucket: 'card-flex.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCUw5vRC8GpYC4ysb--g1owtirpmTPElk',
    appId: '1:459352817410:android:9879e0365fda7fce9ecc1b',
    messagingSenderId: '459352817410',
    projectId: 'card-flex',
    storageBucket: 'card-flex.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr_-KycbE4zOsxFqdLwzvB8GP7CL8G7IM',
    appId: '1:459352817410:ios:8d5be0f460b62cd69ecc1b',
    messagingSenderId: '459352817410',
    projectId: 'card-flex',
    storageBucket: 'card-flex.firebasestorage.app',
    iosBundleId: 'com.example.cardFlex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr_-KycbE4zOsxFqdLwzvB8GP7CL8G7IM',
    appId: '1:459352817410:ios:8d5be0f460b62cd69ecc1b',
    messagingSenderId: '459352817410',
    projectId: 'card-flex',
    storageBucket: 'card-flex.firebasestorage.app',
    iosBundleId: 'com.example.cardFlex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjGXEk49YfYNtqSveFfdBmCgaYJwtolmE',
    appId: '1:459352817410:web:caa7d65761e423ed9ecc1b',
    messagingSenderId: '459352817410',
    projectId: 'card-flex',
    authDomain: 'card-flex.firebaseapp.com',
    storageBucket: 'card-flex.firebasestorage.app',
  );
}
